# Generated by Django 5.0.7 on 2024-08-07 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_chat_recipient_remove_chat_user_chat_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(null=True, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
