# Generated by Django 5.0.7 on 2024-08-12 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chat_new_message_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='update_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='new_message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='new_message_count',
        ),
        migrations.CreateModel(
            name='ChatsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_message_count', models.PositiveSmallIntegerField(default=0)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_log', to='api.chat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chats_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
