# Generated by Django 5.0.7 on 2024-07-29 10:11

import auth_app.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=auth_app.utils.avatar_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alt', models.CharField(default='avatar', max_length=20)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='auth_app.profile')),
            ],
        ),
    ]
