# Generated by Django 5.0.7 on 2024-07-30 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='значение не может быть меньше 0'), django.core.validators.MaxValueValidator(100, message='значение не может быть больше 100')]),
        ),
    ]
