# Generated by Django 5.0.7 on 2024-08-03 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_profile_age_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(blank=True, default='null', error_messages={'max_length': 'значение не может быть больше 20 знаков'}, null=True, validators=[django.core.validators.MaxLengthValidator(20, message='имя: значение не может быть больше 20 знаков'), django.core.validators.RegexValidator('admin', inverse_match=True, message='имя: недопустимое значение')]),
        ),
    ]
